apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-kube-prometheus-grafana-datasource
  namespace: monitoring
  labels:
    grafana_datasource: "1"
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: prometheus
data:
  datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-kube-prometheus-prometheus.monitoring.svc:9090
        isDefault: true
        editable: false










