apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: portfolio-servicemonitor
  namespace: monitoring
  labels:
    release: kps
spec:
  selector:
    matchLabels:
      app: portfolio
      component: backend
  namespaceSelector:
    matchNames:
    - oriyan-portfolio
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
    scheme: http


