apiVersion: apps/v1
kind: Deployment
metadata:
  name: oriyan-portfolio-app
  namespace: oriyan-portfolio
  labels:
    app: portfolio
    component: backend
    owner: oriyan-hemo
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: portfolio
      component: backend
  template:
    metadata:
      labels:
        app: portfolio
        component: backend
        version: v3.0.0
    spec:
      containers:
      - name: portfolio-app
        image: mastereflex123/portfolio:v3.0
        ports:
        - containerPort: 5000
          name: http
        env:
        - name: FLASK_ENV
          value: "production"
        - name: FLASK_DEBUG
          value: "False"
        - name: MONGO_URI
          value: "mongodb://admin:password123@mongodb-service:27017/oriyan_portfolio?authSource=admin"
        - name: SECRET_KEY
          value: "dev-secret-key-2024"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: portfolio-service
  namespace: oriyan-portfolio
  labels:
    app: portfolio
    component: backend
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
    name: http
    nodePort: 30001
  selector:
    app: portfolio
    component: backend
