replicaCount: 2

nameOverride: ""
fullnameOverride: ""

image:
  repository: mastereflex123/portfolio
  tag: "v37-0000360"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 5000
  nodePort: 30001

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "200m"
    memory: "256Mi"

labels:
  app: portfolio
  component: backend
  owner: oriyan-hemo

env:
  flask:
    FLASK_ENV: "production"
    FLASK_DEBUG: "False"
  mongo:
    usernameSecret:
      name: portfolio-secrets
      key: MONGO_USERNAME
    passwordSecret:
      name: portfolio-secrets
      key: MONGO_PASSWORD
    usernameB64: ""
    passwordB64: ""
    uri: '{{ printf "mongodb://%s:%s@%s:%d/%s?authSource=admin" .Values.mongodb.auth.username .Values.mongodb.auth.password "mongodb" 27017 .Values.mongodb.auth.database }}'
  secretKey:
    name: portfolio-secrets
    key: SECRET_KEY

# Subcharts configuration
mongodb:
  enabled: true
  architecture: standalone
  fullnameOverride: mongodb
  auth:
    enabled: true
    rootPassword: "devroot2024"
    username: "portfolio"
    password: "devops2024"
    database: "oriyan_portfolio"
  service:
    port: 27017

probes:
  liveness:
    path: /health
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
  readiness:
    path: /health
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 3

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: portfolio.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

serviceMonitor:
  enabled: true


