replicaCount: 2

labels:
  env: prod

mongodb:
  enabled: true

serviceMonitor:
  enabled: true

service:
  type: ClusterIP

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: portfolio.127.0.0.1.nip.io
      paths:
        - path: /
          pathType: Prefix

replicaCount: 3

labels:
  env: prod

resources:
  requests:
    cpu: "150m"
    memory: "192Mi"
  limits:
    cpu: "300m"
    memory: "384Mi"

mongodb:
  enabled: true

serviceMonitor:
  enabled: true


