replicaCount: 3

labels:
  env: prod

resources:
  requests:
    cpu: "150m"
    memory: "192Mi"
  limits:
    cpu: "300m"
    memory: "384Mi"

mongodb:
  enabled: true

serviceMonitor:
  enabled: true


