controller:
  image: jenkins/jenkins
  tag: lts-jdk17
  adminUser: admin
  adminPassword: devops2024
  overwritePlugins: true
  installPlugins:
    - prometheus:2.0.11
    - git:5.2.1
    - git-client:4.6.0
    - workflow-aggregator:596.v8c21c963d92d
  JCasC:
    defaultConfig: true
    configScripts:
      01-crumb-and-location: |
        jenkins:
          location:
            url: "http://jenkins.local:30080/"
        unclassified:
          crumbIssuer:
            standard:
              excludeClientIPFromCrumb: true
      02-prometheus-config: |
        unclassified:
          prometheus:
            path: "/prometheus"
            useAuthenticatedEndpoint: false
            perBuildMetrics: true
  serviceType: ClusterIP
  ingress:
    enabled: true
    hostName: "jenkins.127.0.0.1.nip.io"
    ingressClassName: nginx
    annotations:
      kubernetes.io/ingress.class: nginx
    tls: []
persistence:
  enabled: true
  size: 8Gi
  accessMode: ReadWriteOnce
  storageClass: standard
agent:
  enabled: false

# Expose Prometheus metrics via chart-native settings (top-level)
prometheus:
  enabled: true
  # attach selector label that Prometheus Operator looks for
  serviceMonitorAdditionalLabels:
    release: prometheus
  # create ServiceMonitor in monitoring ns
  serviceMonitorNamespace: monitoring
  # endpoint path exposed by plugin
  scrapeEndpoint: /prometheus
  resources:
    requests:
      cpu: 300m
      memory: 512Mi
    limits:
      cpu: 600m
      memory: 1Gi
      02-prometheus-config: |
        unclassified:
          prometheusConfiguration:
            path: "prometheus"
            useAuthenticatedEndpoint: false
            perBuildMetrics: true
persistence:
  enabled: true
  size: 8Gi
  accessMode: ReadWriteOnce
  storageClass: standard
agent:
  enabled: false


