apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portfolio-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/MasteRefleX123/devops-portfolio-project.git
    targetRevision: feature/day2-docker-kubernetes
    path: helm/portfolio
    helm:
      valueFiles:
        - helm/portfolio/values.yaml
        - helm/portfolio/values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: portfolio-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true


