apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://charts.jenkins.io
      chart: jenkins
      targetRevision: 4.8.3
      helm:
        valueFiles:
          - $values/jenkins/values.yaml
    - repoURL: https://github.com/MasteRefleX123/devops-portfolio-project.git
      targetRevision: feature/day2-docker-kubernetes
      ref: values
    - repoURL: https://github.com/MasteRefleX123/devops-portfolio-project.git
      targetRevision: feature/day2-docker-kubernetes
      path: jenkins/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
