apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portfolio-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/MasteRefleX123/devops-portfolio-project.git
    targetRevision: feature/day2-docker-kubernetes
    path: helm/portfolio
    helm:
      values: |
        image:
          tag: v35
        replicaCount: 2
        resources:
          requests:
            cpu: "150m"
            memory: "192Mi"
          limits:
            cpu: "300m"
            memory: "384Mi"
  destination:
    server: https://kubernetes.default.svc
    namespace: portfolio-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true


