apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portfolio-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/MasteRefleX123/devops-portfolio-project.git
    targetRevision: feature/day2-docker-kubernetes
    path: helm/portfolio
    helm:
      values: |
        image:
          tag: v37-0000360
        replicaCount: 2
        mongodb:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: portfolio-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true


