{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "oriyan-portfolio.fullname" . }}
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      {{- toYaml .Values.labels | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{- end }}


